sudo: required
language: c
os:
  - linux

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libjansson-dev
  - sudo apt-get install libevent-dev

before_script:  
  - cmake .

script: 
  - make 